name: CI_test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        sourcemod-version: [master]
        metamod-version: [master]
        sdks: [sdk2013, tf2, csgo]

    steps:
      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: project
          
      - name: Checkout Metamod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/metamod-source
          ref: ${{ matrix.metamod-version }}
          path: 'metamod-source'

      - name: Checkout SourceMod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sourcemod-version }}
          path: sourcemod
          submodules: recursive
          
      - name: Checkout SDKs
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: ${{ matrix.sdks }}
          path: hl2sdk-${{ matrix.sdks }}

      - name: Checkout AMBuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        uses: BSFishy/pip-action@v1
        with:
          packages: ./ambuild
          
      - name: Build
        shell: bash
        run: |
          cd project && mkdir build && cd build
          CC=clang CXX=clang++ python ../configure.py --sdks ${{ matrix.sdks }} --enable-optimize
          ambuild
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}
          path: project/extension/build/package